version: '3.7'

networks:
  default:
    driver: bridge

services:

  php:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP_VERSION:-74}
    environment:
      - GITHUB_TOKEN=$GITHUB_TOKEN
    volumes:
      - ./:/var/www/public/
    networks:
      - default
